// react-resume/src/components/header/header.component.jsx
import React from 'react';
import phoneLogo from './../../assets/img/phoneLogo.png';
import mailLogo from './../../assets/img/mailLogo.png';
import gitlogo from './../../assets/img/gitlogo.png';
import linkedinLogo from './../../assets/img/linkedinLogo.png';

const Header = (props) => {
    return (
    <section>
    <h1 class="name">{props.resume.name}</h1>
    <div id="contact">
        <div><img src={phoneLogo}/><a href="tel:{props.resume.phoneNumber}"
                target="_blank">{props.resume.phoneNumber}</a></div>
        <div><img src={mailLogo}/><a href="mailto:{props.resume.email}" target="_blank">{props.resume.email}</a>
        </div>
        <div><img src={gitlogo}/><a href="https://github.com/mohitsparihar/"
                target="_blank">{props.resume.github}</a></div>
        <div><img src={linkedinLogo}/><a href="https://linkedin.com/in/mohitsparihar"
                target="_blank">{props.resume.linkedin}</a></div>
    </div>
    </section>
    )
}

export default Header;

// src/app/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { HttpService } from '../http.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor(private httpService: HttpService) { }
  
  resume: any;

  ngOnInit(): void {
    this.resume = this.httpService.getResumeData();
  }

}

<section>
        <img id="profile-image" src="../../assets/img/profile-pic.JPG" />
        <h1 class="name">{{resume.name}}</h1>
        <div id="contact">
                <div>
                        <img src="assets/img/phoneLogo.png" /><a href="tel:{{resume.phoneNumber}}" target="_blank">{{resume.phoneNumber}}</a>
                </div>
                <div>
                        <img src="assets/img/mailLogo.png" /><a href="mailto:{{resume.email}}" target="_blank">{{resume.email}}</a>
                </div>
                <div>
                        <img src="assets/img/gitlogo.png"><a href="https://github.com/mohitsparihar/" target="_blank">{{resume.github}}</a>
                </div>
                <div>
                        <img src="assets/img/linkedinLogo.png" /><a href="https://linkedin.com/in/mohitsparihar" target="_blank">{{resume.linkedin}}</a>
                </div>
        </div>
</section>
