// react-resume/src/components/education/education.component.jsx
import React from 'react';

const Education = (props) => {
    const items = props.education.map(el => {
        return (
            <li>
            <section>
                <ul>
                    <li>
                        <div class="label">School:</div>
                        <div class="content">{el.school}</div>
                    </li>
                    <li>
                        <div class="label">Program:</div>
                        <div class="content">{el.program}</div>
                    </li>
                    <li>
                        <div class="label">Dates Attended:</div>
                        <div class="content">{el.startDate} - {el.endDate}</div>
                    </li>
                    <li>
                        <div class="label">Achievements:</div>
                        <div class="content">{el.achievements}</div>
                    </li>
                </ul>
            </section>
        </li>
        )
    });

    return (
    <section id="education">
        <h2>Education</h2>
        <ul>
            {items}
        </ul>
    </section>
    )
}

export default Education;

// angular2/src/app/education/education.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-education',
  templateUrl: './education.component.html',
  styleUrls: ['./education.component.scss']
})
export class EducationComponent implements OnInit {

  constructor() { }

  @Input() education: [];

  ngOnInit(): void {
  }

}

<section id="education">
    <h2>Education</h2>
    <ul>
        <li *ngFor="let eduObj of education">
            <section>
                <ul>
                    <li>
                        <div className="label">School:</div>
                        <div className="content">{{eduObj.school}}</div>
                    </li>
                    <li>
                        <div className="label">Program:</div>
                        <div className="content">{{eduObj.program}}</div>
                    </li>
                    <li>
                        <div className="label">Dates Attended:</div>
                        <div className="content">{{eduObj.startDate}} - {{eduObj.endDate}}</div>
                    </li>
                    <li>
                        <div className="label">Achievements:</div>
                        <div className="content">{{eduObj.achievements}}</div>
                    </li>
                </ul>
            </section>
        </li>
    </ul>
</section>
