// react-resume/src/components/personal-project/personal-project.component.jsx
import React from 'react';

const PersonalProjects = (props) => {
    const items = props.personalProjects.map(el => {
        return (
            <li>
                <section>
                    <ul>
                        <li>
                            <div class="label">Name:</div>
                            <div class="content">{el.name}</div>
                        </li>
                        <li>
                            <div class="label">Url:</div>
                            <div class="content"><a href="{el.url}" target="_blank">{el.url}</a></div>
                        </li>
                        <li>
                            <div class="label">Description:</div>
                            <div class="content">{el.description}</div>
                        </li> 
                    </ul>
                    </section>
                </li>
        )
    })

    return (
        <section id="personalProject">
        <h2>Personal Projects</h2>
            <ul>
                {items}
            </ul>
        </section>
    )
}

export default PersonalProjects;

// angular2/src/app/personal-project/personal-project.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-personal-project',
  templateUrl: './personal-project.component.html',
  styleUrls: ['./personal-project.component.scss']
})
export class PersonalProjectComponent implements OnInit {

  constructor() { }

  @Input() personalProjects: [];

  ngOnInit(): void {
  }

}

<section id="personalProject">
    <h2>Personal Projects</h2>
    <ul>
            <li *ngFor="let personalProjectObj of personalProjects">
                <section>
                    <ul>
                        <li>
                            <div class="label">Name:</div>
                            <div class="content">{{personalProjectObj.name}}</div>
                        </li>
                        <li>
                            <div class="label">Url:</div>
                            <div class="content"><a href="{{personalProjectObj.url}}" target="_blank">{{personalProjectObj.url}}</a></div>
                        </li>
                        <li>
                            <div class="label">Description:</div>
                            <div class="content">{{personalProjectObj.description}}</div>
                        </li> 
                    </ul>
                </section>
            </li>
        </ul>
        </section>
