// react-resume/src/App.js
import React from 'react';
import './App.scss';
import resume from './assets/resume';
import Header from './components/header/header.component';
import Objective from './components/objective/objective.component';
import Summary from './components/summary/summary.component';
import Skills from './components/skills/skills.component';
import Projects from './components/projects/projects.component';
import Experience from './components/experience/experience.component';
import PersonalProjects from './components/personal-project/personal-project.component';
import Education from './components/education/education.component';

function App() {
  return (
    <section className="App" id="content">
      <Header resume={resume} />
      <Objective objective={resume.objective} />
      <Summary summary={resume.executiveSummary} />
      <Skills skills={resume.skills}/>
      <Projects projects={resume.projects} />
      <Experience experience={resume.experience} />
      <PersonalProjects personalProjects={resume.personalProjects} />
      <Education education={resume.education} />
    </section>
  );
}

export default App;

// src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from './http.service';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
    title = 'resume';
    resume: any;

    constructor(private httpService: HttpService) { }

    ngOnInit(): void {
        console.log("Oninit call");
        this.httpService.getResume()
            .subscribe(data => {
                this.resume = data;
            })
    }
}

<body>
  <section *ngIf="resume" id="content">
    <app-header [resume]="resume"></app-header>
    <app-objective [resume]="resume"></app-objective>
    <app-summary [resume]="resume"></app-summary>
    <app-skills [skills]="resume.skills"></app-skills>
    <app-projects [projects]="resume.projects"></app-projects>
    <app-experience [experience]="resume.experience"></app-experience>
    <app-personal-project [personalProjects]="resume.personalProjects"></app-personal-project>
    <app-education [education]="resume.education"></app-education>
  </section>
</body>
<router-outlet></router-outlet>
