// src/app/experience/experience.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-experience',
  templateUrl: './experience.component.html',
  styleUrls: ['./experience.component.scss']
})
export class ExperienceComponent implements OnInit {

  constructor() { }

  @Input() experience : [];

  ngOnInit(): void {
  }

}

<section id="experience">
    <h2>Experience</h2>
    <ul>
            <li *ngFor="let expObj of experience">
                <section>
                    <ul>
                        <li>
                            <div class="label">Company Name:</div>
                            <div class="content">{{expObj.name}}</div>
                        </li>
                        <li>
                            <div class="label">Title:</div>
                            <div class="content">{{expObj.title}}</div>
                        </li>
                        <li>
                            <div class="label">Tenure:</div>
                            <div class="content">{{expObj.startDate}} - {{expObj.endDate}}</div>
                        </li>
                        <li>
                            <div class="label">Location:</div>
                            <div class="content">{{expObj.location}}</div>
                        </li>
                        <li>
                            <div class="label">URL:</div>
                            <div class="content">{{expObj.url}}</div>
                        </li>
                    </ul>
                </section>
            </li>
        </ul>
        </section>

// react-resume/src/components/experience/experience.component.jsx
import React from 'react';

const Experience = (props) => {

    const items = props.experience.map(el => {
        return (
            <li>
            <section>
                <ul>
                    <li>
                        <div class="label">Name:</div>
                        <div class="content">{el.name}</div>
                    </li>
                    <li>
                        <div class="label">Title:</div>
                        <div class="content">{el.title}</div>
                    </li>
                    <li>
                        <div class="label">Tenure:</div>
                        <div class="content">{el.startDate} - {el.endDate}</div>
                    </li>
                    <li>
                        <div class="label">Url:</div>
                        <div class="content">{el.url}</div>
                    </li>
                </ul>
            </section>
        </li>
        )
      });
      
    return (
        <section id="experience">
            <h2>Experience</h2>
            <ul>
                {items}
            </ul>
        </section>
    )
};

export default Experience;
