// react-resume/src/components/personal-project/personal-project.component.jsx
import React from 'react';

const PersonalProjects = (props) => {
    const items = props.personalProjects.map(el => {
        return (
            <li>
                <section>
                    <ul>
                        <li>
                            <div class="label">Name:</div>
                            <div class="content">{el.name}</div>
                        </li>
                        <li>
                            <div class="label">Url:</div>
                            <div class="content"><a href="{el.url}" target="_blank">{el.url}</a></div>
                        </li>
                        <li>
                            <div class="label">Description:</div>
                            <div class="content">{el.description}</div>
                        </li> 
                    </ul>
                    </section>
                </li>
        )
    })

    return (
        <section id="personalProject">
        <h2>Personal Projects</h2>
            <ul>
                {items}
            </ul>
        </section>
    )
}

export default PersonalProjects;

// src/app/personal-project/personal-project.component.ts
import { Component, OnInit, Input, OnDestroy } from '@angular/core';
import { HttpService } from '../http.service'
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-personal-project',
  templateUrl: './personal-project.component.html',
  styleUrls: ['./personal-project.component.scss']
})
export class PersonalProjectComponent implements OnInit, OnDestroy {
  personalProjects: [];
  resumeDataSubscription: Subscription;
  constructor(private httpService: HttpService) { }


  ngOnInit(): void {
    this.httpService.getResumeData()
      .subscribe((data: any) => {
        this.personalProjects = data.personalProjects;
      });
  }

  ngOnDestroy(): void {
  }

}

<section id="personalProject" class="content-wrapper">
    <h2>Personal Projects</h2>
    <ul>
            <li *ngFor="let personalProjectObj of personalProjects">
                <section>
                    <ul>
                        <li>
                            <div class="label">Name:</div>
                            <div class="content">{{personalProjectObj.name}}</div>
                        </li>
                        <li>
                            <div class="label">Url:</div>
                            <div class="content"><a href="{{personalProjectObj.url}}" target="_blank">{{personalProjectObj.url}}</a></div>
                        </li>
                        <li>
                            <div class="label">Description:</div>
                            <div class="content">{{personalProjectObj.description}}</div>
                        </li> 
                    </ul>
                </section>
            </li>
        </ul>
        </section>
