// angular2/src/app/projects/projects.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent implements OnInit {

  constructor() { }

  @Input() projects: [];

  ngOnInit(): void {
  }

}

<section id="projects">
    <h2>Projects</h2>
    <ul>
            <li *ngFor="let projectObj of projects">
                <section>
                    <ul>
                        <li>
                            <div className="label">Title:</div>
                            <div className="content">{{projectObj.title}}</div>
                        </li>
                        <li>
                            <div className="label">Technologies:</div>
                            <div className="content">{{projectObj.technologies}}</div>
                        </li>
                        <li>
                            <div className="label">Description:</div>
                            <div className="content">{{projectObj.description}}</div>
                        </li> 
                    </ul>
                </section>
            </li>
        </ul>
        </section>

// react-resume/src/components/projects/projects.component.jsx
import React from 'react';

const Projects = (props) => {
    const items = props.projects.map(el => {
        return (
            <li>
                <section>
                    <ul>
                        <li>
                            <div class="label">Title:</div>
                            <div class="content">{el.title}</div>
                        </li>
                        <li>
                            <div class="label">Technologies:</div>
                            <div class="content">{el.technologies}</div>
                        </li>
                        <li>
                            <div class="label">Description:</div>
                            <div class="content">{el.description}</div>
                        </li> 
                    </ul>
                </section>
            </li>
        )
    });

    return (
    <section id="projects">
        <h2>Projects</h2>
        <ul>
            {items}
        </ul>
    </section>
    )
}

export default Projects;
